"""
AeroCrop.ai — Disease Service

Provides:
  - Authoritative 134-class agricultural pathology taxonomy across 11 core crops
  - Targeted chemical + organic treatment prescriptions
  - Crop-specific severity flags

IMPORTANT: Class indices in DISEASES list match model/classes.json exactly (0 to 133).
"""

from __future__ import annotations
from dataclasses import dataclass, field
from typing import ClassVar


@dataclass
class DiseaseInfo:
    class_idx:   int
    name:        str
    crop:        str
    is_healthy:  bool
    chemical_treatment: list[str] = field(default_factory=list)
    organic_treatment:  list[str] = field(default_factory=list)
    severity:    str = "None"  # None | Low | Moderate | High | Critical
    description: str = ""
    chemical_cost: str = ""
    organic_cost:  str = ""

    @property
    def chemical_cost_display(self) -> str:
        if self.chemical_cost:
            return self.chemical_cost
        return DiseaseService.estimate_chemical_cost(self)

    @property
    def organic_cost_display(self) -> str:
        if self.organic_cost:
            return self.organic_cost
        return DiseaseService.estimate_organic_cost(self)


class DiseaseService:
    """
    Comprehensive service exposing the 134-class pathology knowledge base.
    Class indices match model/classes.json exactly (0 to 133).
    """

    DISEASES: ClassVar[list[DiseaseInfo]] = [
        DiseaseInfo(
            class_idx=0,
            name="Banana \u2014 Anthracnose",
            crop="Banana",
            is_healthy=False,
            chemical_treatment=["Mancozeb 75WP (2.5 g/L)", "Azoxystrobin 18.2% + Difenoconazole 11.4% SC (1 ml/L)", "Carbendazim 12% + Mancozeb 63% WP (Saaf 2 g/L)"],
            organic_treatment=["Neem oil 1500 ppm (3 ml/L)", "Bordeaux mixture 1%", "Trichoderma viride foliar spray (5 g/L)", "Pruning diseased lower leaves"],
            severity="High",
            description="Fungal infection producing circular to irregular chlorotic lesions, necrotic spots, or foliar blighting on Banana leaves.",
        ),
        DiseaseInfo(
            class_idx=1,
            name="Banana \u2014 Black Sigatoka",
            crop="Banana",
            is_healthy=False,
            chemical_treatment=["Mancozeb 75WP (2.5 g/L)", "Azoxystrobin 18.2% + Difenoconazole 11.4% SC (1 ml/L)", "Carbendazim 12% + Mancozeb 63% WP (Saaf 2 g/L)"],
            organic_treatment=["Neem oil 1500 ppm (3 ml/L)", "Bordeaux mixture 1%", "Trichoderma viride foliar spray (5 g/L)", "Pruning diseased lower leaves"],
            severity="Moderate",
            description="Fungal infection producing circular to irregular chlorotic lesions, necrotic spots, or foliar blighting on Banana leaves.",
        ),
        DiseaseInfo(
            class_idx=2,
            name="Banana \u2014 Bract mosaic virus",
            crop="Banana",
            is_healthy=False,
            chemical_treatment=["Thiamethoxam 25WG (0.3 g/L foliar)", "Imidacloprid 17.8SL (0.5 ml/L for vector control)", "Dinotefuran 20SG (0.5 g/L)"],
            organic_treatment=["Rogue and incinerate infected plants", "Yellow/Blue sticky traps (12/acre)", "Reflective silver mulches", "Plant barrier crops (maize/sorghum border)"],
            severity="Critical",
            description="Systemic viral infection in Banana causing mosaic chlorosis, severe leaf curling, stunting, and yield suppression.",
        ),
        DiseaseInfo(
            class_idx=3,
            name="Banana \u2014 Chewing insect",
            crop="Banana",
            is_healthy=False,
            chemical_treatment=["Chlorpyrifos 20EC (2 ml/L)", "Quinalphos 25EC (2 ml/L)", "Lambda-cyhalothrin 5EC (1 ml/L)"],
            organic_treatment=["Neem oil 1500 ppm (3 ml/L)", "Beauveria bassiana (5 g/L)", "Light traps (1/acre)"],
            severity="Moderate",
            description="Insect pest damage characterized by chewing, scratching, or tissue feeding on Banana foliage.",
        ),
        DiseaseInfo(
            class_idx=4,
            name="Banana \u2014 Cordana leaf spot",
            crop="Banana",
            is_healthy=False,
            chemical_treatment=["Mancozeb 75WP (2.5 g/L)", "Azoxystrobin 18.2% + Difenoconazole 11.4% SC (1 ml/L)", "Carbendazim 12% + Mancozeb 63% WP (Saaf 2 g/L)"],
            organic_treatment=["Neem oil 1500 ppm (3 ml/L)", "Bordeaux mixture 1%", "Trichoderma viride foliar spray (5 g/L)", "Pruning diseased lower leaves"],
            severity="Moderate",
            description="Fungal infection producing circular to irregular chlorotic lesions, necrotic spots, or foliar blighting on Banana leaves.",
        ),
        DiseaseInfo(
            class_idx=5,
            name="Banana \u2014 Fruit scarring beetle",
            crop="Banana",
            is_healthy=False,
            chemical_treatment=["Chlorpyrifos 20EC (2 ml/L)", "Quinalphos 25EC (2 ml/L)", "Lambda-cyhalothrin 5EC (1 ml/L)"],
            organic_treatment=["Neem oil 1500 ppm (3 ml/L)", "Beauveria bassiana (5 g/L)", "Light traps (1/acre)"],
            severity="Moderate",
            description="Insect pest damage characterized by chewing, scratching, or tissue feeding on Banana foliage.",
        ),
        DiseaseInfo(
            class_idx=6,
            name="Banana \u2014 Moko disease",
            crop="Banana",
            is_healthy=False,
            chemical_treatment=["Carbendazim 50WP (2 g/L soil drench)", "Metalaxyl 8% + Mancozeb 64% WP (2.5 g/L)", "Thiophanate-Methyl 70WP (1.5 g/L)"],
            organic_treatment=["Trichoderma harzianum soil inoculation (2 kg/acre with FYM)", "Ensure proper drainage ridges", "Seed/Rhizome treatment with bio-agents", "Crop rotation"],
            severity="Critical",
            description="Destructive vascular or root/rhizome pathogen causing internal vascular discoloration, wilting, or decay in Banana.",
        ),
        DiseaseInfo(
            class_idx=7,
            name="Banana \u2014 Panama disease",
            crop="Banana",
            is_healthy=False,
            chemical_treatment=["Carbendazim 50WP (2 g/L soil drench)", "Metalaxyl 8% + Mancozeb 64% WP (2.5 g/L)", "Thiophanate-Methyl 70WP (1.5 g/L)"],
            organic_treatment=["Trichoderma harzianum soil inoculation (2 kg/acre with FYM)", "Ensure proper drainage ridges", "Seed/Rhizome treatment with bio-agents", "Crop rotation"],
            severity="Critical",
            description="Destructive vascular or root/rhizome pathogen causing internal vascular discoloration, wilting, or decay in Banana.",
        ),
        DiseaseInfo(
            class_idx=8,
            name="Banana \u2014 Sigatoka",
            crop="Banana",
            is_healthy=False,
            chemical_treatment=["Mancozeb 75WP (2.5 g/L)", "Azoxystrobin 18.2% + Difenoconazole 11.4% SC (1 ml/L)", "Carbendazim 12% + Mancozeb 63% WP (Saaf 2 g/L)"],
            organic_treatment=["Neem oil 1500 ppm (3 ml/L)", "Bordeaux mixture 1%", "Trichoderma viride foliar spray (5 g/L)", "Pruning diseased lower leaves"],
            severity="Moderate",
            description="Fungal infection producing circular to irregular chlorotic lesions, necrotic spots, or foliar blighting on Banana leaves.",
        ),
        DiseaseInfo(
            class_idx=9,
            name="Banana \u2014 Skipper damage",
            crop="Banana",
            is_healthy=False,
            chemical_treatment=["Chlorpyrifos 20EC (2 ml/L)", "Quinalphos 25EC (2 ml/L)", "Lambda-cyhalothrin 5EC (1 ml/L)"],
            organic_treatment=["Neem oil 1500 ppm (3 ml/L)", "Beauveria bassiana (5 g/L)", "Light traps (1/acre)"],
            severity="Moderate",
            description="Insect pest damage characterized by chewing, scratching, or tissue feeding on Banana foliage.",
        ),
        DiseaseInfo(
            class_idx=10,
            name="Banana \u2014 Split peel",
            crop="Banana",
            is_healthy=False,
            chemical_treatment=["Mancozeb 75WP (2.5 g/L)", "Azoxystrobin 18.2% + Difenoconazole 11.4% SC (1 ml/L)", "Carbendazim 12% + Mancozeb 63% WP (Saaf 2 g/L)"],
            organic_treatment=["Neem oil 1500 ppm (3 ml/L)", "Bordeaux mixture 1%", "Trichoderma viride foliar spray (5 g/L)", "Pruning diseased lower leaves"],
            severity="Moderate",
            description="Fungal infection producing circular to irregular chlorotic lesions, necrotic spots, or foliar blighting on Banana leaves.",
        ),
        DiseaseInfo(
            class_idx=11,
            name="Banana \u2014 Healthy",
            crop="Banana",
            is_healthy=True,
            chemical_treatment=[],
            organic_treatment=[],
            severity="None",
            description="Healthy, vigorous Banana foliage showing robust chlorophyll development with no symptoms of fungal, bacterial, viral infection, or insect pest infestation.",
        ),
        DiseaseInfo(
            class_idx=12,
            name="Maize \u2014 Bacterial leaf streak",
            crop="Maize",
            is_healthy=False,
            chemical_treatment=["Thiamethoxam 25WG (0.3 g/L foliar)", "Imidacloprid 17.8SL (0.5 ml/L for vector control)", "Dinotefuran 20SG (0.5 g/L)"],
            organic_treatment=["Rogue and incinerate infected plants", "Yellow/Blue sticky traps (12/acre)", "Reflective silver mulches", "Plant barrier crops (maize/sorghum border)"],
            severity="Critical",
            description="Systemic viral infection in Maize causing mosaic chlorosis, severe leaf curling, stunting, and yield suppression.",
        ),
        DiseaseInfo(
            class_idx=13,
            name="Maize \u2014 Cercospora leaf spot Gray leaf spot",
            crop="Maize",
            is_healthy=False,
            chemical_treatment=["Mancozeb 75WP (2.5 g/L)", "Azoxystrobin 18.2% + Difenoconazole 11.4% SC (1 ml/L)", "Carbendazim 12% + Mancozeb 63% WP (Saaf 2 g/L)"],
            organic_treatment=["Neem oil 1500 ppm (3 ml/L)", "Bordeaux mixture 1%", "Trichoderma viride foliar spray (5 g/L)", "Pruning diseased lower leaves"],
            severity="Moderate",
            description="Fungal infection producing circular to irregular chlorotic lesions, necrotic spots, or foliar blighting on Maize leaves.",
        ),
        DiseaseInfo(
            class_idx=14,
            name="Maize \u2014 Chlorotic mottle virus",
            crop="Maize",
            is_healthy=False,
            chemical_treatment=["Thiamethoxam 25WG (0.3 g/L foliar)", "Imidacloprid 17.8SL (0.5 ml/L for vector control)", "Dinotefuran 20SG (0.5 g/L)"],
            organic_treatment=["Rogue and incinerate infected plants", "Yellow/Blue sticky traps (12/acre)", "Reflective silver mulches", "Plant barrier crops (maize/sorghum border)"],
            severity="Critical",
            description="Systemic viral infection in Maize causing mosaic chlorosis, severe leaf curling, stunting, and yield suppression.",
        ),
        DiseaseInfo(
            class_idx=15,
            name="Maize \u2014 Common rust ",
            crop="Maize",
            is_healthy=False,
            chemical_treatment=["Propiconazole 25EC (1 ml/L)", "Tebuconazole 25.9EC (1 ml/L)", "Hexaconazole 5EC (1 ml/L)", "Mancozeb 75WP (2 g/L)"],
            organic_treatment=["Sulfur 80WP dusting (2.5 g/L)", "Resistant cultivars", "Avoid dense planting to reduce microclimate humidity"],
            severity="High",
            description="Pathogen characterized by powdery pustules (uredinia/telia) erupting through the epidermal surface of Maize leaves.",
        ),
        DiseaseInfo(
            class_idx=16,
            name="Maize \u2014 Fall armyworm",
            crop="Maize",
            is_healthy=False,
            chemical_treatment=["Emamectin Benzoate 5SG (0.4 g/L)", "Chlorantraniliprole 18.5SC (0.3 ml/L)", "Spinetoram 11.7SC (1 ml/L)"],
            organic_treatment=["Bacillus thuringiensis (Bt) spray (2 g/L)", "Pheromone traps (5/acre)", "Beauveria bassiana (5 g/L)"],
            severity="High",
            description="Aggressive foliar feeding by larvae causing extensive skeletonization and defoliation on Maize leaves.",
        ),
        DiseaseInfo(
            class_idx=17,
            name="Maize \u2014 Grasshopper",
            crop="Maize",
            is_healthy=False,
            chemical_treatment=["Chlorpyrifos 20EC (2 ml/L)", "Quinalphos 25EC (2 ml/L)", "Lambda-cyhalothrin 5EC (1 ml/L)"],
            organic_treatment=["Neem oil 1500 ppm (3 ml/L)", "Beauveria bassiana (5 g/L)", "Light traps (1/acre)"],
            severity="Moderate",
            description="Insect pest damage characterized by chewing, scratching, or tissue feeding on Maize foliage.",
        ),
        DiseaseInfo(
            class_idx=18,
            name="Maize \u2014 Leaf beetle",
            crop="Maize",
            is_healthy=False,
            chemical_treatment=["Chlorpyrifos 20EC (2 ml/L)", "Quinalphos 25EC (2 ml/L)", "Lambda-cyhalothrin 5EC (1 ml/L)"],
            organic_treatment=["Neem oil 1500 ppm (3 ml/L)", "Beauveria bassiana (5 g/L)", "Light traps (1/acre)"],
            severity="Moderate",
            description="Insect pest damage characterized by chewing, scratching, or tissue feeding on Maize foliage.",
        ),
        DiseaseInfo(
            class_idx=19,
            name="Maize \u2014 Lethal necrosis",
            crop="Maize",
            is_healthy=False,
            chemical_treatment=["Mancozeb 75WP (2.5 g/L)", "Azoxystrobin 18.2% + Difenoconazole 11.4% SC (1 ml/L)", "Carbendazim 12% + Mancozeb 63% WP (Saaf 2 g/L)"],
            organic_treatment=["Neem oil 1500 ppm (3 ml/L)", "Bordeaux mixture 1%", "Trichoderma viride foliar spray (5 g/L)", "Pruning diseased lower leaves"],
            severity="Moderate",
            description="Fungal infection producing circular to irregular chlorotic lesions, necrotic spots, or foliar blighting on Maize leaves.",
        ),
        DiseaseInfo(
            class_idx=20,
            name="Maize \u2014 Northern Leaf Blight",
            crop="Maize",
            is_healthy=False,
            chemical_treatment=["Mancozeb 75WP (2.5 g/L)", "Azoxystrobin 18.2% + Difenoconazole 11.4% SC (1 ml/L)", "Carbendazim 12% + Mancozeb 63% WP (Saaf 2 g/L)"],
            organic_treatment=["Neem oil 1500 ppm (3 ml/L)", "Bordeaux mixture 1%", "Trichoderma viride foliar spray (5 g/L)", "Pruning diseased lower leaves"],
            severity="Moderate",
            description="Fungal infection producing circular to irregular chlorotic lesions, necrotic spots, or foliar blighting on Maize leaves.",
        ),
        DiseaseInfo(
            class_idx=21,
            name="Maize \u2014 Streak virus",
            crop="Maize",
            is_healthy=False,
            chemical_treatment=["Thiamethoxam 25WG (0.3 g/L foliar)", "Imidacloprid 17.8SL (0.5 ml/L for vector control)", "Dinotefuran 20SG (0.5 g/L)"],
            organic_treatment=["Rogue and incinerate infected plants", "Yellow/Blue sticky traps (12/acre)", "Reflective silver mulches", "Plant barrier crops (maize/sorghum border)"],
            severity="Critical",
            description="Systemic viral infection in Maize causing mosaic chlorosis, severe leaf curling, stunting, and yield suppression.",
        ),
        DiseaseInfo(
            class_idx=22,
            name="Maize \u2014 Healthy",
            crop="Maize",
            is_healthy=True,
            chemical_treatment=[],
            organic_treatment=[],
            severity="None",
            description="Healthy, vigorous Maize foliage showing robust chlorophyll development with no symptoms of fungal, bacterial, viral infection, or insect pest infestation.",
        ),
        DiseaseInfo(
            class_idx=23,
            name="Cotton \u2014 Alternaria leaf spot",
            crop="Cotton",
            is_healthy=False,
            chemical_treatment=["Mancozeb 75WP (2.5 g/L)", "Azoxystrobin 18.2% + Difenoconazole 11.4% SC (1 ml/L)", "Carbendazim 12% + Mancozeb 63% WP (Saaf 2 g/L)"],
            organic_treatment=["Neem oil 1500 ppm (3 ml/L)", "Bordeaux mixture 1%", "Trichoderma viride foliar spray (5 g/L)", "Pruning diseased lower leaves"],
            severity="Moderate",
            description="Fungal infection producing circular to irregular chlorotic lesions, necrotic spots, or foliar blighting on Cotton leaves.",
        ),
        DiseaseInfo(
            class_idx=24,
            name="Cotton \u2014 Aphid",
            crop="Cotton",
            is_healthy=False,
            chemical_treatment=["Imidacloprid 17.8SL (0.5 ml/L)", "Acetamiprid 20SP (0.2 g/L)", "Thiamethoxam 25WG (0.3 g/L)"],
            organic_treatment=["Neem oil foliar spray (3 ml/L)", "Yellow sticky traps (10/acre)", "Verticillium lecanii bio-agent (5 g/L)"],
            severity="Moderate",
            description="Sucking pest infestation on Cotton causing leaf curling, honeydew excretion, and sooty mold development.",
        ),
        DiseaseInfo(
            class_idx=25,
            name="Cotton \u2014 Army worm",
            crop="Cotton",
            is_healthy=False,
            chemical_treatment=["Mancozeb 75WP (2.5 g/L)", "Azoxystrobin 18.2% + Difenoconazole 11.4% SC (1 ml/L)", "Carbendazim 12% + Mancozeb 63% WP (Saaf 2 g/L)"],
            organic_treatment=["Neem oil 1500 ppm (3 ml/L)", "Bordeaux mixture 1%", "Trichoderma viride foliar spray (5 g/L)", "Pruning diseased lower leaves"],
            severity="Moderate",
            description="Fungal infection producing circular to irregular chlorotic lesions, necrotic spots, or foliar blighting on Cotton leaves.",
        ),
        DiseaseInfo(
            class_idx=26,
            name="Cotton \u2014 Bacterial blight",
            crop="Cotton",
            is_healthy=False,
            chemical_treatment=["Copper Oxychloride 50WP (2.5 g/L) + Streptocycline (0.1 g/L)", "Kasugamycin 3% SL (2 ml/L)", "Copper Hydroxide 53.8DF (2 g/L)"],
            organic_treatment=["Pseudomonas fluorescens (10 g/L spray/drench)", "Avoid overhead irrigation", "Sterilize pruning tools with 10% bleach", "Crop rotation"],
            severity="High",
            description="Bacterial infection causing water-soaked necrotic lesions, vascular wilting, or soft tissue breakdown on Cotton.",
        ),
        DiseaseInfo(
            class_idx=27,
            name="Cotton \u2014 Curl virus",
            crop="Cotton",
            is_healthy=False,
            chemical_treatment=["Thiamethoxam 25WG (0.3 g/L foliar)", "Imidacloprid 17.8SL (0.5 ml/L for vector control)", "Dinotefuran 20SG (0.5 g/L)"],
            organic_treatment=["Rogue and incinerate infected plants", "Yellow/Blue sticky traps (12/acre)", "Reflective silver mulches", "Plant barrier crops (maize/sorghum border)"],
            severity="Critical",
            description="Systemic viral infection in Cotton causing mosaic chlorosis, severe leaf curling, stunting, and yield suppression.",
        ),
        DiseaseInfo(
            class_idx=28,
            name="Cotton \u2014 Diseased leaf",
            crop="Cotton",
            is_healthy=False,
            chemical_treatment=["Mancozeb 75WP (2.5 g/L)", "Azoxystrobin 18.2% + Difenoconazole 11.4% SC (1 ml/L)", "Carbendazim 12% + Mancozeb 63% WP (Saaf 2 g/L)"],
            organic_treatment=["Neem oil 1500 ppm (3 ml/L)", "Bordeaux mixture 1%", "Trichoderma viride foliar spray (5 g/L)", "Pruning diseased lower leaves"],
            severity="Moderate",
            description="Fungal infection producing circular to irregular chlorotic lesions, necrotic spots, or foliar blighting on Cotton leaves.",
        ),
        DiseaseInfo(
            class_idx=29,
            name="Cotton \u2014 Fusarium wilt",
            crop="Cotton",
            is_healthy=False,
            chemical_treatment=["Carbendazim 50WP (2 g/L soil drench)", "Metalaxyl 8% + Mancozeb 64% WP (2.5 g/L)", "Thiophanate-Methyl 70WP (1.5 g/L)"],
            organic_treatment=["Trichoderma harzianum soil inoculation (2 kg/acre with FYM)", "Ensure proper drainage ridges", "Seed/Rhizome treatment with bio-agents", "Crop rotation"],
            severity="Critical",
            description="Destructive vascular or root/rhizome pathogen causing internal vascular discoloration, wilting, or decay in Cotton.",
        ),
        DiseaseInfo(
            class_idx=30,
            name="Cotton \u2014 Herbicide damage",
            crop="Cotton",
            is_healthy=False,
            chemical_treatment=["Mancozeb 75WP (2.5 g/L)", "Azoxystrobin 18.2% + Difenoconazole 11.4% SC (1 ml/L)", "Carbendazim 12% + Mancozeb 63% WP (Saaf 2 g/L)"],
            organic_treatment=["Neem oil 1500 ppm (3 ml/L)", "Bordeaux mixture 1%", "Trichoderma viride foliar spray (5 g/L)", "Pruning diseased lower leaves"],
            severity="Moderate",
            description="Fungal infection producing circular to irregular chlorotic lesions, necrotic spots, or foliar blighting on Cotton leaves.",
        ),
        DiseaseInfo(
            class_idx=31,
            name="Cotton \u2014 Jassid",
            crop="Cotton",
            is_healthy=False,
            chemical_treatment=["Imidacloprid 17.8SL (0.5 ml/L)", "Acetamiprid 20SP (0.2 g/L)", "Thiamethoxam 25WG (0.3 g/L)"],
            organic_treatment=["Neem oil foliar spray (3 ml/L)", "Yellow sticky traps (10/acre)", "Verticillium lecanii bio-agent (5 g/L)"],
            severity="Moderate",
            description="Sucking pest infestation on Cotton causing leaf curling, honeydew excretion, and sooty mold development.",
        ),
        DiseaseInfo(
            class_idx=32,
            name="Cotton \u2014 Leaf reddening",
            crop="Cotton",
            is_healthy=False,
            chemical_treatment=["Mancozeb 75WP (2.5 g/L)", "Azoxystrobin 18.2% + Difenoconazole 11.4% SC (1 ml/L)", "Carbendazim 12% + Mancozeb 63% WP (Saaf 2 g/L)"],
            organic_treatment=["Neem oil 1500 ppm (3 ml/L)", "Bordeaux mixture 1%", "Trichoderma viride foliar spray (5 g/L)", "Pruning diseased lower leaves"],
            severity="Moderate",
            description="Fungal infection producing circular to irregular chlorotic lesions, necrotic spots, or foliar blighting on Cotton leaves.",
        ),
        DiseaseInfo(
            class_idx=33,
            name="Cotton \u2014 Leaf variegation",
            crop="Cotton",
            is_healthy=False,
            chemical_treatment=["Mancozeb 75WP (2.5 g/L)", "Azoxystrobin 18.2% + Difenoconazole 11.4% SC (1 ml/L)", "Carbendazim 12% + Mancozeb 63% WP (Saaf 2 g/L)"],
            organic_treatment=["Neem oil 1500 ppm (3 ml/L)", "Bordeaux mixture 1%", "Trichoderma viride foliar spray (5 g/L)", "Pruning diseased lower leaves"],
            severity="Moderate",
            description="Fungal infection producing circular to irregular chlorotic lesions, necrotic spots, or foliar blighting on Cotton leaves.",
        ),
        DiseaseInfo(
            class_idx=34,
            name="Cotton \u2014 Powdery mildew",
            crop="Cotton",
            is_healthy=False,
            chemical_treatment=["Mancozeb 75WP (2.5 g/L)", "Azoxystrobin 18.2% + Difenoconazole 11.4% SC (1 ml/L)", "Carbendazim 12% + Mancozeb 63% WP (Saaf 2 g/L)"],
            organic_treatment=["Neem oil 1500 ppm (3 ml/L)", "Bordeaux mixture 1%", "Trichoderma viride foliar spray (5 g/L)", "Pruning diseased lower leaves"],
            severity="Moderate",
            description="Fungal infection producing circular to irregular chlorotic lesions, necrotic spots, or foliar blighting on Cotton leaves.",
        ),
        DiseaseInfo(
            class_idx=35,
            name="Cotton \u2014 Target spot",
            crop="Cotton",
            is_healthy=False,
            chemical_treatment=["Mancozeb 75WP (2.5 g/L)", "Azoxystrobin 18.2% + Difenoconazole 11.4% SC (1 ml/L)", "Carbendazim 12% + Mancozeb 63% WP (Saaf 2 g/L)"],
            organic_treatment=["Neem oil 1500 ppm (3 ml/L)", "Bordeaux mixture 1%", "Trichoderma viride foliar spray (5 g/L)", "Pruning diseased lower leaves"],
            severity="Moderate",
            description="Fungal infection producing circular to irregular chlorotic lesions, necrotic spots, or foliar blighting on Cotton leaves.",
        ),
        DiseaseInfo(
            class_idx=36,
            name="Cotton \u2014 Verticillium wilt",
            crop="Cotton",
            is_healthy=False,
            chemical_treatment=["Carbendazim 50WP (2 g/L soil drench)", "Metalaxyl 8% + Mancozeb 64% WP (2.5 g/L)", "Thiophanate-Methyl 70WP (1.5 g/L)"],
            organic_treatment=["Trichoderma harzianum soil inoculation (2 kg/acre with FYM)", "Ensure proper drainage ridges", "Seed/Rhizome treatment with bio-agents", "Crop rotation"],
            severity="Critical",
            description="Destructive vascular or root/rhizome pathogen causing internal vascular discoloration, wilting, or decay in Cotton.",
        ),
        DiseaseInfo(
            class_idx=37,
            name="Cotton \u2014 Healthy",
            crop="Cotton",
            is_healthy=True,
            chemical_treatment=[],
            organic_treatment=[],
            severity="None",
            description="Healthy, vigorous Cotton foliage showing robust chlorophyll development with no symptoms of fungal, bacterial, viral infection, or insect pest infestation.",
        ),
        DiseaseInfo(
            class_idx=38,
            name="Orange \u2014 Black spot",
            crop="Orange",
            is_healthy=False,
            chemical_treatment=["Mancozeb 75WP (2.5 g/L)", "Azoxystrobin 18.2% + Difenoconazole 11.4% SC (1 ml/L)", "Carbendazim 12% + Mancozeb 63% WP (Saaf 2 g/L)"],
            organic_treatment=["Neem oil 1500 ppm (3 ml/L)", "Bordeaux mixture 1%", "Trichoderma viride foliar spray (5 g/L)", "Pruning diseased lower leaves"],
            severity="Moderate",
            description="Fungal infection producing circular to irregular chlorotic lesions, necrotic spots, or foliar blighting on Orange leaves.",
        ),
        DiseaseInfo(
            class_idx=39,
            name="Orange \u2014 Canker",
            crop="Orange",
            is_healthy=False,
            chemical_treatment=["Copper Oxychloride 50WP (2.5 g/L) + Streptocycline (0.1 g/L)", "Kasugamycin 3% SL (2 ml/L)", "Copper Hydroxide 53.8DF (2 g/L)"],
            organic_treatment=["Pseudomonas fluorescens (10 g/L spray/drench)", "Avoid overhead irrigation", "Sterilize pruning tools with 10% bleach", "Crop rotation"],
            severity="High",
            description="Bacterial infection causing water-soaked necrotic lesions, vascular wilting, or soft tissue breakdown on Orange.",
        ),
        DiseaseInfo(
            class_idx=40,
            name="Orange \u2014 Citrus mealybug",
            crop="Orange",
            is_healthy=False,
            chemical_treatment=["Imidacloprid 17.8SL (0.5 ml/L)", "Acetamiprid 20SP (0.2 g/L)", "Thiamethoxam 25WG (0.3 g/L)"],
            organic_treatment=["Neem oil foliar spray (3 ml/L)", "Yellow sticky traps (10/acre)", "Verticillium lecanii bio-agent (5 g/L)"],
            severity="Moderate",
            description="Sucking pest infestation on Orange causing leaf curling, honeydew excretion, and sooty mold development.",
        ),
        DiseaseInfo(
            class_idx=41,
            name="Orange \u2014 Die back",
            crop="Orange",
            is_healthy=False,
            chemical_treatment=["Mancozeb 75WP (2.5 g/L)", "Azoxystrobin 18.2% + Difenoconazole 11.4% SC (1 ml/L)", "Carbendazim 12% + Mancozeb 63% WP (Saaf 2 g/L)"],
            organic_treatment=["Neem oil 1500 ppm (3 ml/L)", "Bordeaux mixture 1%", "Trichoderma viride foliar spray (5 g/L)", "Pruning diseased lower leaves"],
            severity="Moderate",
            description="Fungal infection producing circular to irregular chlorotic lesions, necrotic spots, or foliar blighting on Orange leaves.",
        ),
        DiseaseInfo(
            class_idx=42,
            name="Orange \u2014 Foliage damage",
            crop="Orange",
            is_healthy=False,
            chemical_treatment=["Mancozeb 75WP (2.5 g/L)", "Azoxystrobin 18.2% + Difenoconazole 11.4% SC (1 ml/L)", "Carbendazim 12% + Mancozeb 63% WP (Saaf 2 g/L)"],
            organic_treatment=["Neem oil 1500 ppm (3 ml/L)", "Bordeaux mixture 1%", "Trichoderma viride foliar spray (5 g/L)", "Pruning diseased lower leaves"],
            severity="Moderate",
            description="Fungal infection producing circular to irregular chlorotic lesions, necrotic spots, or foliar blighting on Orange leaves.",
        ),
        DiseaseInfo(
            class_idx=43,
            name="Orange \u2014 Haunglongbing (Citrus greening)",
            crop="Orange",
            is_healthy=False,
            chemical_treatment=["Mancozeb 75WP (2.5 g/L)", "Azoxystrobin 18.2% + Difenoconazole 11.4% SC (1 ml/L)", "Carbendazim 12% + Mancozeb 63% WP (Saaf 2 g/L)"],
            organic_treatment=["Neem oil 1500 ppm (3 ml/L)", "Bordeaux mixture 1%", "Trichoderma viride foliar spray (5 g/L)", "Pruning diseased lower leaves"],
            severity="Moderate",
            description="Fungal infection producing circular to irregular chlorotic lesions, necrotic spots, or foliar blighting on Orange leaves.",
        ),
        DiseaseInfo(
            class_idx=44,
            name="Orange \u2014 Melanose",
            crop="Orange",
            is_healthy=False,
            chemical_treatment=["Mancozeb 75WP (2.5 g/L)", "Azoxystrobin 18.2% + Difenoconazole 11.4% SC (1 ml/L)", "Carbendazim 12% + Mancozeb 63% WP (Saaf 2 g/L)"],
            organic_treatment=["Neem oil 1500 ppm (3 ml/L)", "Bordeaux mixture 1%", "Trichoderma viride foliar spray (5 g/L)", "Pruning diseased lower leaves"],
            severity="Moderate",
            description="Fungal infection producing circular to irregular chlorotic lesions, necrotic spots, or foliar blighting on Orange leaves.",
        ),
        DiseaseInfo(
            class_idx=45,
            name="Orange \u2014 Powdery mildew",
            crop="Orange",
            is_healthy=False,
            chemical_treatment=["Mancozeb 75WP (2.5 g/L)", "Azoxystrobin 18.2% + Difenoconazole 11.4% SC (1 ml/L)", "Carbendazim 12% + Mancozeb 63% WP (Saaf 2 g/L)"],
            organic_treatment=["Neem oil 1500 ppm (3 ml/L)", "Bordeaux mixture 1%", "Trichoderma viride foliar spray (5 g/L)", "Pruning diseased lower leaves"],
            severity="Moderate",
            description="Fungal infection producing circular to irregular chlorotic lesions, necrotic spots, or foliar blighting on Orange leaves.",
        ),
        DiseaseInfo(
            class_idx=46,
            name="Orange \u2014 Scab",
            crop="Orange",
            is_healthy=False,
            chemical_treatment=["Mancozeb 75WP (2.5 g/L)", "Azoxystrobin 18.2% + Difenoconazole 11.4% SC (1 ml/L)", "Carbendazim 12% + Mancozeb 63% WP (Saaf 2 g/L)"],
            organic_treatment=["Neem oil 1500 ppm (3 ml/L)", "Bordeaux mixture 1%", "Trichoderma viride foliar spray (5 g/L)", "Pruning diseased lower leaves"],
            severity="Moderate",
            description="Fungal infection producing circular to irregular chlorotic lesions, necrotic spots, or foliar blighting on Orange leaves.",
        ),
        DiseaseInfo(
            class_idx=47,
            name="Orange \u2014 Shot hole",
            crop="Orange",
            is_healthy=False,
            chemical_treatment=["Mancozeb 75WP (2.5 g/L)", "Azoxystrobin 18.2% + Difenoconazole 11.4% SC (1 ml/L)", "Carbendazim 12% + Mancozeb 63% WP (Saaf 2 g/L)"],
            organic_treatment=["Neem oil 1500 ppm (3 ml/L)", "Bordeaux mixture 1%", "Trichoderma viride foliar spray (5 g/L)", "Pruning diseased lower leaves"],
            severity="Moderate",
            description="Fungal infection producing circular to irregular chlorotic lesions, necrotic spots, or foliar blighting on Orange leaves.",
        ),
        DiseaseInfo(
            class_idx=48,
            name="Orange \u2014 Spiny whitefly",
            crop="Orange",
            is_healthy=False,
            chemical_treatment=["Imidacloprid 17.8SL (0.5 ml/L)", "Acetamiprid 20SP (0.2 g/L)", "Thiamethoxam 25WG (0.3 g/L)"],
            organic_treatment=["Neem oil foliar spray (3 ml/L)", "Yellow sticky traps (10/acre)", "Verticillium lecanii bio-agent (5 g/L)"],
            severity="Moderate",
            description="Sucking pest infestation on Orange causing leaf curling, honeydew excretion, and sooty mold development.",
        ),
        DiseaseInfo(
            class_idx=49,
            name="Orange \u2014 Yellow leaves",
            crop="Orange",
            is_healthy=False,
            chemical_treatment=["Mancozeb 75WP (2.5 g/L)", "Azoxystrobin 18.2% + Difenoconazole 11.4% SC (1 ml/L)", "Carbendazim 12% + Mancozeb 63% WP (Saaf 2 g/L)"],
            organic_treatment=["Neem oil 1500 ppm (3 ml/L)", "Bordeaux mixture 1%", "Trichoderma viride foliar spray (5 g/L)", "Pruning diseased lower leaves"],
            severity="Moderate",
            description="Fungal infection producing circular to irregular chlorotic lesions, necrotic spots, or foliar blighting on Orange leaves.",
        ),
        DiseaseInfo(
            class_idx=50,
            name="Orange \u2014 Healthy",
            crop="Orange",
            is_healthy=True,
            chemical_treatment=[],
            organic_treatment=[],
            severity="None",
            description="Healthy, vigorous Orange foliage showing robust chlorophyll development with no symptoms of fungal, bacterial, viral infection, or insect pest infestation.",
        ),
        DiseaseInfo(
            class_idx=51,
            name="Potato \u2014 Bacterial soft rot",
            crop="Potato",
            is_healthy=False,
            chemical_treatment=["Copper Oxychloride 50WP (2.5 g/L) + Streptocycline (0.1 g/L)", "Kasugamycin 3% SL (2 ml/L)", "Copper Hydroxide 53.8DF (2 g/L)"],
            organic_treatment=["Pseudomonas fluorescens (10 g/L spray/drench)", "Avoid overhead irrigation", "Sterilize pruning tools with 10% bleach", "Crop rotation"],
            severity="High",
            description="Bacterial infection causing water-soaked necrotic lesions, vascular wilting, or soft tissue breakdown on Potato.",
        ),
        DiseaseInfo(
            class_idx=52,
            name="Potato \u2014 Bacterial wilt",
            crop="Potato",
            is_healthy=False,
            chemical_treatment=["Copper Oxychloride 50WP (2.5 g/L) + Streptocycline (0.1 g/L)", "Kasugamycin 3% SL (2 ml/L)", "Copper Hydroxide 53.8DF (2 g/L)"],
            organic_treatment=["Pseudomonas fluorescens (10 g/L spray/drench)", "Avoid overhead irrigation", "Sterilize pruning tools with 10% bleach", "Crop rotation"],
            severity="High",
            description="Bacterial infection causing water-soaked necrotic lesions, vascular wilting, or soft tissue breakdown on Potato.",
        ),
        DiseaseInfo(
            class_idx=53,
            name="Potato \u2014 Black scurf",
            crop="Potato",
            is_healthy=False,
            chemical_treatment=["Mancozeb 75WP (2.5 g/L)", "Azoxystrobin 18.2% + Difenoconazole 11.4% SC (1 ml/L)", "Carbendazim 12% + Mancozeb 63% WP (Saaf 2 g/L)"],
            organic_treatment=["Neem oil 1500 ppm (3 ml/L)", "Bordeaux mixture 1%", "Trichoderma viride foliar spray (5 g/L)", "Pruning diseased lower leaves"],
            severity="Moderate",
            description="Fungal infection producing circular to irregular chlorotic lesions, necrotic spots, or foliar blighting on Potato leaves.",
        ),
        DiseaseInfo(
            class_idx=54,
            name="Potato \u2014 Blackleg",
            crop="Potato",
            is_healthy=False,
            chemical_treatment=["Copper Oxychloride 50WP (2.5 g/L) + Streptocycline (0.1 g/L)", "Kasugamycin 3% SL (2 ml/L)", "Copper Hydroxide 53.8DF (2 g/L)"],
            organic_treatment=["Pseudomonas fluorescens (10 g/L spray/drench)", "Avoid overhead irrigation", "Sterilize pruning tools with 10% bleach", "Crop rotation"],
            severity="High",
            description="Bacterial infection causing water-soaked necrotic lesions, vascular wilting, or soft tissue breakdown on Potato.",
        ),
        DiseaseInfo(
            class_idx=55,
            name="Potato \u2014 Blackspot bruising",
            crop="Potato",
            is_healthy=False,
            chemical_treatment=["Mancozeb 75WP (2.5 g/L)", "Azoxystrobin 18.2% + Difenoconazole 11.4% SC (1 ml/L)", "Carbendazim 12% + Mancozeb 63% WP (Saaf 2 g/L)"],
            organic_treatment=["Neem oil 1500 ppm (3 ml/L)", "Bordeaux mixture 1%", "Trichoderma viride foliar spray (5 g/L)", "Pruning diseased lower leaves"],
            severity="Moderate",
            description="Fungal infection producing circular to irregular chlorotic lesions, necrotic spots, or foliar blighting on Potato leaves.",
        ),
        DiseaseInfo(
            class_idx=56,
            name="Potato \u2014 Common scab",
            crop="Potato",
            is_healthy=False,
            chemical_treatment=["Mancozeb 75WP (2.5 g/L)", "Azoxystrobin 18.2% + Difenoconazole 11.4% SC (1 ml/L)", "Carbendazim 12% + Mancozeb 63% WP (Saaf 2 g/L)"],
            organic_treatment=["Neem oil 1500 ppm (3 ml/L)", "Bordeaux mixture 1%", "Trichoderma viride foliar spray (5 g/L)", "Pruning diseased lower leaves"],
            severity="Moderate",
            description="Fungal infection producing circular to irregular chlorotic lesions, necrotic spots, or foliar blighting on Potato leaves.",
        ),
        DiseaseInfo(
            class_idx=57,
            name="Potato \u2014 Dry rot",
            crop="Potato",
            is_healthy=False,
            chemical_treatment=["Mancozeb 75WP (2.5 g/L)", "Azoxystrobin 18.2% + Difenoconazole 11.4% SC (1 ml/L)", "Carbendazim 12% + Mancozeb 63% WP (Saaf 2 g/L)"],
            organic_treatment=["Neem oil 1500 ppm (3 ml/L)", "Bordeaux mixture 1%", "Trichoderma viride foliar spray (5 g/L)", "Pruning diseased lower leaves"],
            severity="Moderate",
            description="Fungal infection producing circular to irregular chlorotic lesions, necrotic spots, or foliar blighting on Potato leaves.",
        ),
        DiseaseInfo(
            class_idx=58,
            name="Potato \u2014 Early blight",
            crop="Potato",
            is_healthy=False,
            chemical_treatment=["Mancozeb 75WP (2.5 g/L)", "Azoxystrobin 18.2% + Difenoconazole 11.4% SC (1 ml/L)", "Carbendazim 12% + Mancozeb 63% WP (Saaf 2 g/L)"],
            organic_treatment=["Neem oil 1500 ppm (3 ml/L)", "Bordeaux mixture 1%", "Trichoderma viride foliar spray (5 g/L)", "Pruning diseased lower leaves"],
            severity="Moderate",
            description="Fungal infection producing circular to irregular chlorotic lesions, necrotic spots, or foliar blighting on Potato leaves.",
        ),
        DiseaseInfo(
            class_idx=59,
            name="Potato \u2014 Fungal disease",
            crop="Potato",
            is_healthy=False,
            chemical_treatment=["Mancozeb 75WP (2.5 g/L)", "Azoxystrobin 18.2% + Difenoconazole 11.4% SC (1 ml/L)", "Carbendazim 12% + Mancozeb 63% WP (Saaf 2 g/L)"],
            organic_treatment=["Neem oil 1500 ppm (3 ml/L)", "Bordeaux mixture 1%", "Trichoderma viride foliar spray (5 g/L)", "Pruning diseased lower leaves"],
            severity="Moderate",
            description="Fungal infection producing circular to irregular chlorotic lesions, necrotic spots, or foliar blighting on Potato leaves.",
        ),
        DiseaseInfo(
            class_idx=60,
            name="Potato \u2014 Late blight",
            crop="Potato",
            is_healthy=False,
            chemical_treatment=["Mancozeb 75WP (2.5 g/L)", "Azoxystrobin 18.2% + Difenoconazole 11.4% SC (1 ml/L)", "Carbendazim 12% + Mancozeb 63% WP (Saaf 2 g/L)"],
            organic_treatment=["Neem oil 1500 ppm (3 ml/L)", "Bordeaux mixture 1%", "Trichoderma viride foliar spray (5 g/L)", "Pruning diseased lower leaves"],
            severity="Critical",
            description="Fungal infection producing circular to irregular chlorotic lesions, necrotic spots, or foliar blighting on Potato leaves.",
        ),
        DiseaseInfo(
            class_idx=61,
            name="Potato \u2014 Leaf roll virus",
            crop="Potato",
            is_healthy=False,
            chemical_treatment=["Thiamethoxam 25WG (0.3 g/L foliar)", "Imidacloprid 17.8SL (0.5 ml/L for vector control)", "Dinotefuran 20SG (0.5 g/L)"],
            organic_treatment=["Rogue and incinerate infected plants", "Yellow/Blue sticky traps (12/acre)", "Reflective silver mulches", "Plant barrier crops (maize/sorghum border)"],
            severity="Critical",
            description="Systemic viral infection in Potato causing mosaic chlorosis, severe leaf curling, stunting, and yield suppression.",
        ),
        DiseaseInfo(
            class_idx=62,
            name="Potato \u2014 Mosaic virus",
            crop="Potato",
            is_healthy=False,
            chemical_treatment=["Thiamethoxam 25WG (0.3 g/L foliar)", "Imidacloprid 17.8SL (0.5 ml/L for vector control)", "Dinotefuran 20SG (0.5 g/L)"],
            organic_treatment=["Rogue and incinerate infected plants", "Yellow/Blue sticky traps (12/acre)", "Reflective silver mulches", "Plant barrier crops (maize/sorghum border)"],
            severity="Critical",
            description="Systemic viral infection in Potato causing mosaic chlorosis, severe leaf curling, stunting, and yield suppression.",
        ),
        DiseaseInfo(
            class_idx=63,
            name="Potato \u2014 Nematode",
            crop="Potato",
            is_healthy=False,
            chemical_treatment=["Chlorpyrifos 20EC (2 ml/L)", "Quinalphos 25EC (2 ml/L)", "Lambda-cyhalothrin 5EC (1 ml/L)"],
            organic_treatment=["Neem oil 1500 ppm (3 ml/L)", "Beauveria bassiana (5 g/L)", "Light traps (1/acre)"],
            severity="Moderate",
            description="Insect pest damage characterized by chewing, scratching, or tissue feeding on Potato foliage.",
        ),
        DiseaseInfo(
            class_idx=64,
            name="Potato \u2014 Pest damage",
            crop="Potato",
            is_healthy=False,
            chemical_treatment=["Mancozeb 75WP (2.5 g/L)", "Azoxystrobin 18.2% + Difenoconazole 11.4% SC (1 ml/L)", "Carbendazim 12% + Mancozeb 63% WP (Saaf 2 g/L)"],
            organic_treatment=["Neem oil 1500 ppm (3 ml/L)", "Bordeaux mixture 1%", "Trichoderma viride foliar spray (5 g/L)", "Pruning diseased lower leaves"],
            severity="Moderate",
            description="Fungal infection producing circular to irregular chlorotic lesions, necrotic spots, or foliar blighting on Potato leaves.",
        ),
        DiseaseInfo(
            class_idx=65,
            name="Potato \u2014 Pink rot",
            crop="Potato",
            is_healthy=False,
            chemical_treatment=["Mancozeb 75WP (2.5 g/L)", "Azoxystrobin 18.2% + Difenoconazole 11.4% SC (1 ml/L)", "Carbendazim 12% + Mancozeb 63% WP (Saaf 2 g/L)"],
            organic_treatment=["Neem oil 1500 ppm (3 ml/L)", "Bordeaux mixture 1%", "Trichoderma viride foliar spray (5 g/L)", "Pruning diseased lower leaves"],
            severity="Moderate",
            description="Fungal infection producing circular to irregular chlorotic lesions, necrotic spots, or foliar blighting on Potato leaves.",
        ),
        DiseaseInfo(
            class_idx=66,
            name="Potato \u2014 Potato virus X",
            crop="Potato",
            is_healthy=False,
            chemical_treatment=["Thiamethoxam 25WG (0.3 g/L foliar)", "Imidacloprid 17.8SL (0.5 ml/L for vector control)", "Dinotefuran 20SG (0.5 g/L)"],
            organic_treatment=["Rogue and incinerate infected plants", "Yellow/Blue sticky traps (12/acre)", "Reflective silver mulches", "Plant barrier crops (maize/sorghum border)"],
            severity="Critical",
            description="Systemic viral infection in Potato causing mosaic chlorosis, severe leaf curling, stunting, and yield suppression.",
        ),
        DiseaseInfo(
            class_idx=67,
            name="Potato \u2014 Potato virus Y",
            crop="Potato",
            is_healthy=False,
            chemical_treatment=["Thiamethoxam 25WG (0.3 g/L foliar)", "Imidacloprid 17.8SL (0.5 ml/L for vector control)", "Dinotefuran 20SG (0.5 g/L)"],
            organic_treatment=["Rogue and incinerate infected plants", "Yellow/Blue sticky traps (12/acre)", "Reflective silver mulches", "Plant barrier crops (maize/sorghum border)"],
            severity="Critical",
            description="Systemic viral infection in Potato causing mosaic chlorosis, severe leaf curling, stunting, and yield suppression.",
        ),
        DiseaseInfo(
            class_idx=68,
            name="Potato \u2014 Healthy",
            crop="Potato",
            is_healthy=True,
            chemical_treatment=[],
            organic_treatment=[],
            severity="None",
            description="Healthy, vigorous Potato foliage showing robust chlorophyll development with no symptoms of fungal, bacterial, viral infection, or insect pest infestation.",
        ),
        DiseaseInfo(
            class_idx=69,
            name="Rice \u2014 Bacterial leaf blight",
            crop="Rice",
            is_healthy=False,
            chemical_treatment=["Copper Oxychloride 50WP (2.5 g/L) + Streptocycline (0.1 g/L)", "Kasugamycin 3% SL (2 ml/L)", "Copper Hydroxide 53.8DF (2 g/L)"],
            organic_treatment=["Pseudomonas fluorescens (10 g/L spray/drench)", "Avoid overhead irrigation", "Sterilize pruning tools with 10% bleach", "Crop rotation"],
            severity="High",
            description="Bacterial infection causing water-soaked necrotic lesions, vascular wilting, or soft tissue breakdown on Rice.",
        ),
        DiseaseInfo(
            class_idx=70,
            name="Rice \u2014 Bacterial leaf streak",
            crop="Rice",
            is_healthy=False,
            chemical_treatment=["Thiamethoxam 25WG (0.3 g/L foliar)", "Imidacloprid 17.8SL (0.5 ml/L for vector control)", "Dinotefuran 20SG (0.5 g/L)"],
            organic_treatment=["Rogue and incinerate infected plants", "Yellow/Blue sticky traps (12/acre)", "Reflective silver mulches", "Plant barrier crops (maize/sorghum border)"],
            severity="Critical",
            description="Systemic viral infection in Rice causing mosaic chlorosis, severe leaf curling, stunting, and yield suppression.",
        ),
        DiseaseInfo(
            class_idx=71,
            name="Rice \u2014 Bacterial panicle blight",
            crop="Rice",
            is_healthy=False,
            chemical_treatment=["Copper Oxychloride 50WP (2.5 g/L) + Streptocycline (0.1 g/L)", "Kasugamycin 3% SL (2 ml/L)", "Copper Hydroxide 53.8DF (2 g/L)"],
            organic_treatment=["Pseudomonas fluorescens (10 g/L spray/drench)", "Avoid overhead irrigation", "Sterilize pruning tools with 10% bleach", "Crop rotation"],
            severity="High",
            description="Bacterial infection causing water-soaked necrotic lesions, vascular wilting, or soft tissue breakdown on Rice.",
        ),
        DiseaseInfo(
            class_idx=72,
            name="Rice \u2014 Brown spot",
            crop="Rice",
            is_healthy=False,
            chemical_treatment=["Mancozeb 75WP (2.5 g/L)", "Azoxystrobin 18.2% + Difenoconazole 11.4% SC (1 ml/L)", "Carbendazim 12% + Mancozeb 63% WP (Saaf 2 g/L)"],
            organic_treatment=["Neem oil 1500 ppm (3 ml/L)", "Bordeaux mixture 1%", "Trichoderma viride foliar spray (5 g/L)", "Pruning diseased lower leaves"],
            severity="Moderate",
            description="Fungal infection producing circular to irregular chlorotic lesions, necrotic spots, or foliar blighting on Rice leaves.",
        ),
        DiseaseInfo(
            class_idx=73,
            name="Rice \u2014 Dead heart",
            crop="Rice",
            is_healthy=False,
            chemical_treatment=["Mancozeb 75WP (2.5 g/L)", "Azoxystrobin 18.2% + Difenoconazole 11.4% SC (1 ml/L)", "Carbendazim 12% + Mancozeb 63% WP (Saaf 2 g/L)"],
            organic_treatment=["Neem oil 1500 ppm (3 ml/L)", "Bordeaux mixture 1%", "Trichoderma viride foliar spray (5 g/L)", "Pruning diseased lower leaves"],
            severity="Moderate",
            description="Fungal infection producing circular to irregular chlorotic lesions, necrotic spots, or foliar blighting on Rice leaves.",
        ),
        DiseaseInfo(
            class_idx=74,
            name="Rice \u2014 Downy mildew",
            crop="Rice",
            is_healthy=False,
            chemical_treatment=["Mancozeb 75WP (2.5 g/L)", "Azoxystrobin 18.2% + Difenoconazole 11.4% SC (1 ml/L)", "Carbendazim 12% + Mancozeb 63% WP (Saaf 2 g/L)"],
            organic_treatment=["Neem oil 1500 ppm (3 ml/L)", "Bordeaux mixture 1%", "Trichoderma viride foliar spray (5 g/L)", "Pruning diseased lower leaves"],
            severity="Moderate",
            description="Fungal infection producing circular to irregular chlorotic lesions, necrotic spots, or foliar blighting on Rice leaves.",
        ),
        DiseaseInfo(
            class_idx=75,
            name="Rice \u2014 Hispa",
            crop="Rice",
            is_healthy=False,
            chemical_treatment=["Chlorpyrifos 20EC (2 ml/L)", "Quinalphos 25EC (2 ml/L)", "Lambda-cyhalothrin 5EC (1 ml/L)"],
            organic_treatment=["Neem oil 1500 ppm (3 ml/L)", "Beauveria bassiana (5 g/L)", "Light traps (1/acre)"],
            severity="Moderate",
            description="Insect pest damage characterized by chewing, scratching, or tissue feeding on Rice foliage.",
        ),
        DiseaseInfo(
            class_idx=76,
            name="Rice \u2014 Leaf blast",
            crop="Rice",
            is_healthy=False,
            chemical_treatment=["Mancozeb 75WP (2.5 g/L)", "Azoxystrobin 18.2% + Difenoconazole 11.4% SC (1 ml/L)", "Carbendazim 12% + Mancozeb 63% WP (Saaf 2 g/L)"],
            organic_treatment=["Neem oil 1500 ppm (3 ml/L)", "Bordeaux mixture 1%", "Trichoderma viride foliar spray (5 g/L)", "Pruning diseased lower leaves"],
            severity="High",
            description="Fungal infection producing circular to irregular chlorotic lesions, necrotic spots, or foliar blighting on Rice leaves.",
        ),
        DiseaseInfo(
            class_idx=77,
            name="Rice \u2014 Leaf smut",
            crop="Rice",
            is_healthy=False,
            chemical_treatment=["Propiconazole 25EC (1 ml/L)", "Tebuconazole 25.9EC (1 ml/L)", "Hexaconazole 5EC (1 ml/L)", "Mancozeb 75WP (2 g/L)"],
            organic_treatment=["Sulfur 80WP dusting (2.5 g/L)", "Resistant cultivars", "Avoid dense planting to reduce microclimate humidity"],
            severity="High",
            description="Pathogen characterized by powdery pustules (uredinia/telia) erupting through the epidermal surface of Rice leaves.",
        ),
        DiseaseInfo(
            class_idx=78,
            name="Rice \u2014 Tungro",
            crop="Rice",
            is_healthy=False,
            chemical_treatment=["Thiamethoxam 25WG (0.3 g/L foliar)", "Imidacloprid 17.8SL (0.5 ml/L for vector control)", "Dinotefuran 20SG (0.5 g/L)"],
            organic_treatment=["Rogue and incinerate infected plants", "Yellow/Blue sticky traps (12/acre)", "Reflective silver mulches", "Plant barrier crops (maize/sorghum border)"],
            severity="Critical",
            description="Systemic viral infection in Rice causing mosaic chlorosis, severe leaf curling, stunting, and yield suppression.",
        ),
        DiseaseInfo(
            class_idx=79,
            name="Rice \u2014 Healthy",
            crop="Rice",
            is_healthy=True,
            chemical_treatment=[],
            organic_treatment=[],
            severity="None",
            description="Healthy, vigorous Rice foliage showing robust chlorophyll development with no symptoms of fungal, bacterial, viral infection, or insect pest infestation.",
        ),
        DiseaseInfo(
            class_idx=80,
            name="Soybean \u2014 Bacterial blight",
            crop="Soybean",
            is_healthy=False,
            chemical_treatment=["Copper Oxychloride 50WP (2.5 g/L) + Streptocycline (0.1 g/L)", "Kasugamycin 3% SL (2 ml/L)", "Copper Hydroxide 53.8DF (2 g/L)"],
            organic_treatment=["Pseudomonas fluorescens (10 g/L spray/drench)", "Avoid overhead irrigation", "Sterilize pruning tools with 10% bleach", "Crop rotation"],
            severity="High",
            description="Bacterial infection causing water-soaked necrotic lesions, vascular wilting, or soft tissue breakdown on Soybean.",
        ),
        DiseaseInfo(
            class_idx=81,
            name="Soybean \u2014 Brown spot",
            crop="Soybean",
            is_healthy=False,
            chemical_treatment=["Mancozeb 75WP (2.5 g/L)", "Azoxystrobin 18.2% + Difenoconazole 11.4% SC (1 ml/L)", "Carbendazim 12% + Mancozeb 63% WP (Saaf 2 g/L)"],
            organic_treatment=["Neem oil 1500 ppm (3 ml/L)", "Bordeaux mixture 1%", "Trichoderma viride foliar spray (5 g/L)", "Pruning diseased lower leaves"],
            severity="Moderate",
            description="Fungal infection producing circular to irregular chlorotic lesions, necrotic spots, or foliar blighting on Soybean leaves.",
        ),
        DiseaseInfo(
            class_idx=82,
            name="Soybean \u2014 Caterpillar",
            crop="Soybean",
            is_healthy=False,
            chemical_treatment=["Emamectin Benzoate 5SG (0.4 g/L)", "Chlorantraniliprole 18.5SC (0.3 ml/L)", "Spinetoram 11.7SC (1 ml/L)"],
            organic_treatment=["Bacillus thuringiensis (Bt) spray (2 g/L)", "Pheromone traps (5/acre)", "Beauveria bassiana (5 g/L)"],
            severity="High",
            description="Aggressive foliar feeding by larvae causing extensive skeletonization and defoliation on Soybean leaves.",
        ),
        DiseaseInfo(
            class_idx=83,
            name="Soybean \u2014 Cercospora leaf blight",
            crop="Soybean",
            is_healthy=False,
            chemical_treatment=["Mancozeb 75WP (2.5 g/L)", "Azoxystrobin 18.2% + Difenoconazole 11.4% SC (1 ml/L)", "Carbendazim 12% + Mancozeb 63% WP (Saaf 2 g/L)"],
            organic_treatment=["Neem oil 1500 ppm (3 ml/L)", "Bordeaux mixture 1%", "Trichoderma viride foliar spray (5 g/L)", "Pruning diseased lower leaves"],
            severity="Moderate",
            description="Fungal infection producing circular to irregular chlorotic lesions, necrotic spots, or foliar blighting on Soybean leaves.",
        ),
        DiseaseInfo(
            class_idx=84,
            name="Soybean \u2014 Dry leaf",
            crop="Soybean",
            is_healthy=False,
            chemical_treatment=["Mancozeb 75WP (2.5 g/L)", "Azoxystrobin 18.2% + Difenoconazole 11.4% SC (1 ml/L)", "Carbendazim 12% + Mancozeb 63% WP (Saaf 2 g/L)"],
            organic_treatment=["Neem oil 1500 ppm (3 ml/L)", "Bordeaux mixture 1%", "Trichoderma viride foliar spray (5 g/L)", "Pruning diseased lower leaves"],
            severity="Moderate",
            description="Fungal infection producing circular to irregular chlorotic lesions, necrotic spots, or foliar blighting on Soybean leaves.",
        ),
        DiseaseInfo(
            class_idx=85,
            name="Soybean \u2014 Frogeye leaf spot",
            crop="Soybean",
            is_healthy=False,
            chemical_treatment=["Mancozeb 75WP (2.5 g/L)", "Azoxystrobin 18.2% + Difenoconazole 11.4% SC (1 ml/L)", "Carbendazim 12% + Mancozeb 63% WP (Saaf 2 g/L)"],
            organic_treatment=["Neem oil 1500 ppm (3 ml/L)", "Bordeaux mixture 1%", "Trichoderma viride foliar spray (5 g/L)", "Pruning diseased lower leaves"],
            severity="Moderate",
            description="Fungal infection producing circular to irregular chlorotic lesions, necrotic spots, or foliar blighting on Soybean leaves.",
        ),
        DiseaseInfo(
            class_idx=86,
            name="Soybean \u2014 Mosaic virus",
            crop="Soybean",
            is_healthy=False,
            chemical_treatment=["Thiamethoxam 25WG (0.3 g/L foliar)", "Imidacloprid 17.8SL (0.5 ml/L for vector control)", "Dinotefuran 20SG (0.5 g/L)"],
            organic_treatment=["Rogue and incinerate infected plants", "Yellow/Blue sticky traps (12/acre)", "Reflective silver mulches", "Plant barrier crops (maize/sorghum border)"],
            severity="Critical",
            description="Systemic viral infection in Soybean causing mosaic chlorosis, severe leaf curling, stunting, and yield suppression.",
        ),
        DiseaseInfo(
            class_idx=87,
            name="Soybean \u2014 Rust",
            crop="Soybean",
            is_healthy=False,
            chemical_treatment=["Propiconazole 25EC (1 ml/L)", "Tebuconazole 25.9EC (1 ml/L)", "Hexaconazole 5EC (1 ml/L)", "Mancozeb 75WP (2 g/L)"],
            organic_treatment=["Sulfur 80WP dusting (2.5 g/L)", "Resistant cultivars", "Avoid dense planting to reduce microclimate humidity"],
            severity="High",
            description="Pathogen characterized by powdery pustules (uredinia/telia) erupting through the epidermal surface of Soybean leaves.",
        ),
        DiseaseInfo(
            class_idx=88,
            name="Soybean \u2014 Sudden death syndrome",
            crop="Soybean",
            is_healthy=False,
            chemical_treatment=["Mancozeb 75WP (2.5 g/L)", "Azoxystrobin 18.2% + Difenoconazole 11.4% SC (1 ml/L)", "Carbendazim 12% + Mancozeb 63% WP (Saaf 2 g/L)"],
            organic_treatment=["Neem oil 1500 ppm (3 ml/L)", "Bordeaux mixture 1%", "Trichoderma viride foliar spray (5 g/L)", "Pruning diseased lower leaves"],
            severity="Moderate",
            description="Fungal infection producing circular to irregular chlorotic lesions, necrotic spots, or foliar blighting on Soybean leaves.",
        ),
        DiseaseInfo(
            class_idx=89,
            name="Soybean \u2014 Vein necrosis",
            crop="Soybean",
            is_healthy=False,
            chemical_treatment=["Mancozeb 75WP (2.5 g/L)", "Azoxystrobin 18.2% + Difenoconazole 11.4% SC (1 ml/L)", "Carbendazim 12% + Mancozeb 63% WP (Saaf 2 g/L)"],
            organic_treatment=["Neem oil 1500 ppm (3 ml/L)", "Bordeaux mixture 1%", "Trichoderma viride foliar spray (5 g/L)", "Pruning diseased lower leaves"],
            severity="Moderate",
            description="Fungal infection producing circular to irregular chlorotic lesions, necrotic spots, or foliar blighting on Soybean leaves.",
        ),
        DiseaseInfo(
            class_idx=90,
            name="Soybean \u2014 Healthy",
            crop="Soybean",
            is_healthy=True,
            chemical_treatment=[],
            organic_treatment=[],
            severity="None",
            description="Healthy, vigorous Soybean foliage showing robust chlorophyll development with no symptoms of fungal, bacterial, viral infection, or insect pest infestation.",
        ),
        DiseaseInfo(
            class_idx=91,
            name="Sugarcane \u2014 Banded chlorosis",
            crop="Sugarcane",
            is_healthy=False,
            chemical_treatment=["Mancozeb 75WP (2.5 g/L)", "Azoxystrobin 18.2% + Difenoconazole 11.4% SC (1 ml/L)", "Carbendazim 12% + Mancozeb 63% WP (Saaf 2 g/L)"],
            organic_treatment=["Neem oil 1500 ppm (3 ml/L)", "Bordeaux mixture 1%", "Trichoderma viride foliar spray (5 g/L)", "Pruning diseased lower leaves"],
            severity="Moderate",
            description="Fungal infection producing circular to irregular chlorotic lesions, necrotic spots, or foliar blighting on Sugarcane leaves.",
        ),
        DiseaseInfo(
            class_idx=92,
            name="Sugarcane \u2014 Brown spot",
            crop="Sugarcane",
            is_healthy=False,
            chemical_treatment=["Mancozeb 75WP (2.5 g/L)", "Azoxystrobin 18.2% + Difenoconazole 11.4% SC (1 ml/L)", "Carbendazim 12% + Mancozeb 63% WP (Saaf 2 g/L)"],
            organic_treatment=["Neem oil 1500 ppm (3 ml/L)", "Bordeaux mixture 1%", "Trichoderma viride foliar spray (5 g/L)", "Pruning diseased lower leaves"],
            severity="Moderate",
            description="Fungal infection producing circular to irregular chlorotic lesions, necrotic spots, or foliar blighting on Sugarcane leaves.",
        ),
        DiseaseInfo(
            class_idx=93,
            name="Sugarcane \u2014 Dried leaf",
            crop="Sugarcane",
            is_healthy=False,
            chemical_treatment=["Mancozeb 75WP (2.5 g/L)", "Azoxystrobin 18.2% + Difenoconazole 11.4% SC (1 ml/L)", "Carbendazim 12% + Mancozeb 63% WP (Saaf 2 g/L)"],
            organic_treatment=["Neem oil 1500 ppm (3 ml/L)", "Bordeaux mixture 1%", "Trichoderma viride foliar spray (5 g/L)", "Pruning diseased lower leaves"],
            severity="Moderate",
            description="Fungal infection producing circular to irregular chlorotic lesions, necrotic spots, or foliar blighting on Sugarcane leaves.",
        ),
        DiseaseInfo(
            class_idx=94,
            name="Sugarcane \u2014 Grassy shoot",
            crop="Sugarcane",
            is_healthy=False,
            chemical_treatment=["Mancozeb 75WP (2.5 g/L)", "Azoxystrobin 18.2% + Difenoconazole 11.4% SC (1 ml/L)", "Carbendazim 12% + Mancozeb 63% WP (Saaf 2 g/L)"],
            organic_treatment=["Neem oil 1500 ppm (3 ml/L)", "Bordeaux mixture 1%", "Trichoderma viride foliar spray (5 g/L)", "Pruning diseased lower leaves"],
            severity="Moderate",
            description="Fungal infection producing circular to irregular chlorotic lesions, necrotic spots, or foliar blighting on Sugarcane leaves.",
        ),
        DiseaseInfo(
            class_idx=95,
            name="Sugarcane \u2014 Mosaic",
            crop="Sugarcane",
            is_healthy=False,
            chemical_treatment=["Thiamethoxam 25WG (0.3 g/L foliar)", "Imidacloprid 17.8SL (0.5 ml/L for vector control)", "Dinotefuran 20SG (0.5 g/L)"],
            organic_treatment=["Rogue and incinerate infected plants", "Yellow/Blue sticky traps (12/acre)", "Reflective silver mulches", "Plant barrier crops (maize/sorghum border)"],
            severity="Critical",
            description="Systemic viral infection in Sugarcane causing mosaic chlorosis, severe leaf curling, stunting, and yield suppression.",
        ),
        DiseaseInfo(
            class_idx=96,
            name="Sugarcane \u2014 Pokkah boeng",
            crop="Sugarcane",
            is_healthy=False,
            chemical_treatment=["Mancozeb 75WP (2.5 g/L)", "Azoxystrobin 18.2% + Difenoconazole 11.4% SC (1 ml/L)", "Carbendazim 12% + Mancozeb 63% WP (Saaf 2 g/L)"],
            organic_treatment=["Neem oil 1500 ppm (3 ml/L)", "Bordeaux mixture 1%", "Trichoderma viride foliar spray (5 g/L)", "Pruning diseased lower leaves"],
            severity="Moderate",
            description="Fungal infection producing circular to irregular chlorotic lesions, necrotic spots, or foliar blighting on Sugarcane leaves.",
        ),
        DiseaseInfo(
            class_idx=97,
            name="Sugarcane \u2014 Red rot",
            crop="Sugarcane",
            is_healthy=False,
            chemical_treatment=["Mancozeb 75WP (2.5 g/L)", "Azoxystrobin 18.2% + Difenoconazole 11.4% SC (1 ml/L)", "Carbendazim 12% + Mancozeb 63% WP (Saaf 2 g/L)"],
            organic_treatment=["Neem oil 1500 ppm (3 ml/L)", "Bordeaux mixture 1%", "Trichoderma viride foliar spray (5 g/L)", "Pruning diseased lower leaves"],
            severity="Moderate",
            description="Fungal infection producing circular to irregular chlorotic lesions, necrotic spots, or foliar blighting on Sugarcane leaves.",
        ),
        DiseaseInfo(
            class_idx=98,
            name="Sugarcane \u2014 Rust",
            crop="Sugarcane",
            is_healthy=False,
            chemical_treatment=["Propiconazole 25EC (1 ml/L)", "Tebuconazole 25.9EC (1 ml/L)", "Hexaconazole 5EC (1 ml/L)", "Mancozeb 75WP (2 g/L)"],
            organic_treatment=["Sulfur 80WP dusting (2.5 g/L)", "Resistant cultivars", "Avoid dense planting to reduce microclimate humidity"],
            severity="High",
            description="Pathogen characterized by powdery pustules (uredinia/telia) erupting through the epidermal surface of Sugarcane leaves.",
        ),
        DiseaseInfo(
            class_idx=99,
            name="Sugarcane \u2014 Sett rot",
            crop="Sugarcane",
            is_healthy=False,
            chemical_treatment=["Mancozeb 75WP (2.5 g/L)", "Azoxystrobin 18.2% + Difenoconazole 11.4% SC (1 ml/L)", "Carbendazim 12% + Mancozeb 63% WP (Saaf 2 g/L)"],
            organic_treatment=["Neem oil 1500 ppm (3 ml/L)", "Bordeaux mixture 1%", "Trichoderma viride foliar spray (5 g/L)", "Pruning diseased lower leaves"],
            severity="Moderate",
            description="Fungal infection producing circular to irregular chlorotic lesions, necrotic spots, or foliar blighting on Sugarcane leaves.",
        ),
        DiseaseInfo(
            class_idx=100,
            name="Sugarcane \u2014 Smut",
            crop="Sugarcane",
            is_healthy=False,
            chemical_treatment=["Propiconazole 25EC (1 ml/L)", "Tebuconazole 25.9EC (1 ml/L)", "Hexaconazole 5EC (1 ml/L)", "Mancozeb 75WP (2 g/L)"],
            organic_treatment=["Sulfur 80WP dusting (2.5 g/L)", "Resistant cultivars", "Avoid dense planting to reduce microclimate humidity"],
            severity="High",
            description="Pathogen characterized by powdery pustules (uredinia/telia) erupting through the epidermal surface of Sugarcane leaves.",
        ),
        DiseaseInfo(
            class_idx=101,
            name="Sugarcane \u2014 Yellow leaf",
            crop="Sugarcane",
            is_healthy=False,
            chemical_treatment=["Mancozeb 75WP (2.5 g/L)", "Azoxystrobin 18.2% + Difenoconazole 11.4% SC (1 ml/L)", "Carbendazim 12% + Mancozeb 63% WP (Saaf 2 g/L)"],
            organic_treatment=["Neem oil 1500 ppm (3 ml/L)", "Bordeaux mixture 1%", "Trichoderma viride foliar spray (5 g/L)", "Pruning diseased lower leaves"],
            severity="Moderate",
            description="Fungal infection producing circular to irregular chlorotic lesions, necrotic spots, or foliar blighting on Sugarcane leaves.",
        ),
        DiseaseInfo(
            class_idx=102,
            name="Sugarcane \u2014 Healthy",
            crop="Sugarcane",
            is_healthy=True,
            chemical_treatment=[],
            organic_treatment=[],
            severity="None",
            description="Healthy, vigorous Sugarcane foliage showing robust chlorophyll development with no symptoms of fungal, bacterial, viral infection, or insect pest infestation.",
        ),
        DiseaseInfo(
            class_idx=103,
            name="Tomato \u2014 Bacterial spot",
            crop="Tomato",
            is_healthy=False,
            chemical_treatment=["Copper Oxychloride 50WP (2.5 g/L) + Streptocycline (0.1 g/L)", "Kasugamycin 3% SL (2 ml/L)", "Copper Hydroxide 53.8DF (2 g/L)"],
            organic_treatment=["Pseudomonas fluorescens (10 g/L spray/drench)", "Avoid overhead irrigation", "Sterilize pruning tools with 10% bleach", "Crop rotation"],
            severity="High",
            description="Bacterial infection causing water-soaked necrotic lesions, vascular wilting, or soft tissue breakdown on Tomato.",
        ),
        DiseaseInfo(
            class_idx=104,
            name="Tomato \u2014 Early blight",
            crop="Tomato",
            is_healthy=False,
            chemical_treatment=["Mancozeb 75WP (2.5 g/L)", "Azoxystrobin 18.2% + Difenoconazole 11.4% SC (1 ml/L)", "Carbendazim 12% + Mancozeb 63% WP (Saaf 2 g/L)"],
            organic_treatment=["Neem oil 1500 ppm (3 ml/L)", "Bordeaux mixture 1%", "Trichoderma viride foliar spray (5 g/L)", "Pruning diseased lower leaves"],
            severity="Moderate",
            description="Fungal infection producing circular to irregular chlorotic lesions, necrotic spots, or foliar blighting on Tomato leaves.",
        ),
        DiseaseInfo(
            class_idx=105,
            name="Tomato \u2014 Late blight",
            crop="Tomato",
            is_healthy=False,
            chemical_treatment=["Mancozeb 75WP (2.5 g/L)", "Azoxystrobin 18.2% + Difenoconazole 11.4% SC (1 ml/L)", "Carbendazim 12% + Mancozeb 63% WP (Saaf 2 g/L)"],
            organic_treatment=["Neem oil 1500 ppm (3 ml/L)", "Bordeaux mixture 1%", "Trichoderma viride foliar spray (5 g/L)", "Pruning diseased lower leaves"],
            severity="Critical",
            description="Fungal infection producing circular to irregular chlorotic lesions, necrotic spots, or foliar blighting on Tomato leaves.",
        ),
        DiseaseInfo(
            class_idx=106,
            name="Tomato \u2014 Leaf Mold",
            crop="Tomato",
            is_healthy=False,
            chemical_treatment=["Mancozeb 75WP (2.5 g/L)", "Azoxystrobin 18.2% + Difenoconazole 11.4% SC (1 ml/L)", "Carbendazim 12% + Mancozeb 63% WP (Saaf 2 g/L)"],
            organic_treatment=["Neem oil 1500 ppm (3 ml/L)", "Bordeaux mixture 1%", "Trichoderma viride foliar spray (5 g/L)", "Pruning diseased lower leaves"],
            severity="Moderate",
            description="Fungal infection producing circular to irregular chlorotic lesions, necrotic spots, or foliar blighting on Tomato leaves.",
        ),
        DiseaseInfo(
            class_idx=107,
            name="Tomato \u2014 Septoria leaf spot",
            crop="Tomato",
            is_healthy=False,
            chemical_treatment=["Mancozeb 75WP (2.5 g/L)", "Azoxystrobin 18.2% + Difenoconazole 11.4% SC (1 ml/L)", "Carbendazim 12% + Mancozeb 63% WP (Saaf 2 g/L)"],
            organic_treatment=["Neem oil 1500 ppm (3 ml/L)", "Bordeaux mixture 1%", "Trichoderma viride foliar spray (5 g/L)", "Pruning diseased lower leaves"],
            severity="Moderate",
            description="Fungal infection producing circular to irregular chlorotic lesions, necrotic spots, or foliar blighting on Tomato leaves.",
        ),
        DiseaseInfo(
            class_idx=108,
            name="Tomato \u2014 Spider mites Two-spotted spider mite",
            crop="Tomato",
            is_healthy=False,
            chemical_treatment=["Spiromesifen 22.9SC (1 ml/L)", "Propargite 57EC (2 ml/L)", "Abamectin 1.9EC (0.5 ml/L)"],
            organic_treatment=["Neem oil 1500 ppm (3 ml/L)", "Wettable sulfur (2.5 g/L)", "Predatory mites (Phytoseiidae)"],
            severity="Moderate",
            description="Mite infestation causing micro-punctures on Tomato leaves, resulting in stippling, webbing, and bronzing.",
        ),
        DiseaseInfo(
            class_idx=109,
            name="Tomato \u2014 Target Spot",
            crop="Tomato",
            is_healthy=False,
            chemical_treatment=["Mancozeb 75WP (2.5 g/L)", "Azoxystrobin 18.2% + Difenoconazole 11.4% SC (1 ml/L)", "Carbendazim 12% + Mancozeb 63% WP (Saaf 2 g/L)"],
            organic_treatment=["Neem oil 1500 ppm (3 ml/L)", "Bordeaux mixture 1%", "Trichoderma viride foliar spray (5 g/L)", "Pruning diseased lower leaves"],
            severity="Moderate",
            description="Fungal infection producing circular to irregular chlorotic lesions, necrotic spots, or foliar blighting on Tomato leaves.",
        ),
        DiseaseInfo(
            class_idx=110,
            name="Tomato \u2014 Tomato Yellow Leaf Curl Virus",
            crop="Tomato",
            is_healthy=False,
            chemical_treatment=["Thiamethoxam 25WG (0.3 g/L foliar)", "Imidacloprid 17.8SL (0.5 ml/L for vector control)", "Dinotefuran 20SG (0.5 g/L)"],
            organic_treatment=["Rogue and incinerate infected plants", "Yellow/Blue sticky traps (12/acre)", "Reflective silver mulches", "Plant barrier crops (maize/sorghum border)"],
            severity="Critical",
            description="Systemic viral infection in Tomato causing mosaic chlorosis, severe leaf curling, stunting, and yield suppression.",
        ),
        DiseaseInfo(
            class_idx=111,
            name="Tomato \u2014 Tomato mosaic virus",
            crop="Tomato",
            is_healthy=False,
            chemical_treatment=["Thiamethoxam 25WG (0.3 g/L foliar)", "Imidacloprid 17.8SL (0.5 ml/L for vector control)", "Dinotefuran 20SG (0.5 g/L)"],
            organic_treatment=["Rogue and incinerate infected plants", "Yellow/Blue sticky traps (12/acre)", "Reflective silver mulches", "Plant barrier crops (maize/sorghum border)"],
            severity="Critical",
            description="Systemic viral infection in Tomato causing mosaic chlorosis, severe leaf curling, stunting, and yield suppression.",
        ),
        DiseaseInfo(
            class_idx=112,
            name="Tomato \u2014 Healthy",
            crop="Tomato",
            is_healthy=True,
            chemical_treatment=[],
            organic_treatment=[],
            severity="None",
            description="Healthy, vigorous Tomato foliage showing robust chlorophyll development with no symptoms of fungal, bacterial, viral infection, or insect pest infestation.",
        ),
        DiseaseInfo(
            class_idx=113,
            name="Turmeric \u2014 Aphid",
            crop="Turmeric",
            is_healthy=False,
            chemical_treatment=["Imidacloprid 17.8SL (0.5 ml/L)", "Acetamiprid 20SP (0.2 g/L)", "Thiamethoxam 25WG (0.3 g/L)"],
            organic_treatment=["Neem oil foliar spray (3 ml/L)", "Yellow sticky traps (10/acre)", "Verticillium lecanii bio-agent (5 g/L)"],
            severity="Moderate",
            description="Sucking pest infestation on Turmeric causing leaf curling, honeydew excretion, and sooty mold development.",
        ),
        DiseaseInfo(
            class_idx=114,
            name="Turmeric \u2014 Dry leaf",
            crop="Turmeric",
            is_healthy=False,
            chemical_treatment=["Mancozeb 75WP (2.5 g/L)", "Azoxystrobin 18.2% + Difenoconazole 11.4% SC (1 ml/L)", "Carbendazim 12% + Mancozeb 63% WP (Saaf 2 g/L)"],
            organic_treatment=["Neem oil 1500 ppm (3 ml/L)", "Bordeaux mixture 1%", "Trichoderma viride foliar spray (5 g/L)", "Pruning diseased lower leaves"],
            severity="Moderate",
            description="Fungal infection producing circular to irregular chlorotic lesions, necrotic spots, or foliar blighting on Turmeric leaves.",
        ),
        DiseaseInfo(
            class_idx=115,
            name="Turmeric \u2014 Leaf blotch mild",
            crop="Turmeric",
            is_healthy=False,
            chemical_treatment=["Mancozeb 75WP (2.5 g/L)", "Azoxystrobin 18.2% + Difenoconazole 11.4% SC (1 ml/L)", "Carbendazim 12% + Mancozeb 63% WP (Saaf 2 g/L)"],
            organic_treatment=["Neem oil 1500 ppm (3 ml/L)", "Bordeaux mixture 1%", "Trichoderma viride foliar spray (5 g/L)", "Pruning diseased lower leaves"],
            severity="Moderate",
            description="Fungal infection producing circular to irregular chlorotic lesions, necrotic spots, or foliar blighting on Turmeric leaves.",
        ),
        DiseaseInfo(
            class_idx=116,
            name="Turmeric \u2014 Leaf blotch severe",
            crop="Turmeric",
            is_healthy=False,
            chemical_treatment=["Mancozeb 75WP (2.5 g/L)", "Azoxystrobin 18.2% + Difenoconazole 11.4% SC (1 ml/L)", "Carbendazim 12% + Mancozeb 63% WP (Saaf 2 g/L)"],
            organic_treatment=["Neem oil 1500 ppm (3 ml/L)", "Bordeaux mixture 1%", "Trichoderma viride foliar spray (5 g/L)", "Pruning diseased lower leaves"],
            severity="High",
            description="Fungal infection producing circular to irregular chlorotic lesions, necrotic spots, or foliar blighting on Turmeric leaves.",
        ),
        DiseaseInfo(
            class_idx=117,
            name="Turmeric \u2014 Leaf spot mild",
            crop="Turmeric",
            is_healthy=False,
            chemical_treatment=["Mancozeb 75WP (2.5 g/L)", "Azoxystrobin 18.2% + Difenoconazole 11.4% SC (1 ml/L)", "Carbendazim 12% + Mancozeb 63% WP (Saaf 2 g/L)"],
            organic_treatment=["Neem oil 1500 ppm (3 ml/L)", "Bordeaux mixture 1%", "Trichoderma viride foliar spray (5 g/L)", "Pruning diseased lower leaves"],
            severity="Moderate",
            description="Fungal infection producing circular to irregular chlorotic lesions, necrotic spots, or foliar blighting on Turmeric leaves.",
        ),
        DiseaseInfo(
            class_idx=118,
            name="Turmeric \u2014 Leaf spot severe",
            crop="Turmeric",
            is_healthy=False,
            chemical_treatment=["Mancozeb 75WP (2.5 g/L)", "Azoxystrobin 18.2% + Difenoconazole 11.4% SC (1 ml/L)", "Carbendazim 12% + Mancozeb 63% WP (Saaf 2 g/L)"],
            organic_treatment=["Neem oil 1500 ppm (3 ml/L)", "Bordeaux mixture 1%", "Trichoderma viride foliar spray (5 g/L)", "Pruning diseased lower leaves"],
            severity="High",
            description="Fungal infection producing circular to irregular chlorotic lesions, necrotic spots, or foliar blighting on Turmeric leaves.",
        ),
        DiseaseInfo(
            class_idx=119,
            name="Turmeric \u2014 Healthy",
            crop="Turmeric",
            is_healthy=True,
            chemical_treatment=[],
            organic_treatment=[],
            severity="None",
            description="Healthy, vigorous Turmeric foliage showing robust chlorophyll development with no symptoms of fungal, bacterial, viral infection, or insect pest infestation.",
        ),
        DiseaseInfo(
            class_idx=120,
            name="Turmeric \u2014 Rhizome rot early",
            crop="Turmeric",
            is_healthy=False,
            chemical_treatment=["Mancozeb 75WP (2.5 g/L)", "Azoxystrobin 18.2% + Difenoconazole 11.4% SC (1 ml/L)", "Carbendazim 12% + Mancozeb 63% WP (Saaf 2 g/L)"],
            organic_treatment=["Neem oil 1500 ppm (3 ml/L)", "Bordeaux mixture 1%", "Trichoderma viride foliar spray (5 g/L)", "Pruning diseased lower leaves"],
            severity="Moderate",
            description="Fungal infection producing circular to irregular chlorotic lesions, necrotic spots, or foliar blighting on Turmeric leaves.",
        ),
        DiseaseInfo(
            class_idx=121,
            name="Turmeric \u2014 Rhizome rot severe",
            crop="Turmeric",
            is_healthy=False,
            chemical_treatment=["Mancozeb 75WP (2.5 g/L)", "Azoxystrobin 18.2% + Difenoconazole 11.4% SC (1 ml/L)", "Carbendazim 12% + Mancozeb 63% WP (Saaf 2 g/L)"],
            organic_treatment=["Neem oil 1500 ppm (3 ml/L)", "Bordeaux mixture 1%", "Trichoderma viride foliar spray (5 g/L)", "Pruning diseased lower leaves"],
            severity="High",
            description="Fungal infection producing circular to irregular chlorotic lesions, necrotic spots, or foliar blighting on Turmeric leaves.",
        ),
        DiseaseInfo(
            class_idx=122,
            name="Turmeric \u2014 Healthy",
            crop="Turmeric",
            is_healthy=True,
            chemical_treatment=[],
            organic_treatment=[],
            severity="None",
            description="Healthy, vigorous Turmeric foliage showing robust chlorophyll development with no symptoms of fungal, bacterial, viral infection, or insect pest infestation.",
        ),
        DiseaseInfo(
            class_idx=123,
            name="Wheat \u2014 Aphid",
            crop="Wheat",
            is_healthy=False,
            chemical_treatment=["Imidacloprid 17.8SL (0.5 ml/L)", "Acetamiprid 20SP (0.2 g/L)", "Thiamethoxam 25WG (0.3 g/L)"],
            organic_treatment=["Neem oil foliar spray (3 ml/L)", "Yellow sticky traps (10/acre)", "Verticillium lecanii bio-agent (5 g/L)"],
            severity="Moderate",
            description="Sucking pest infestation on Wheat causing leaf curling, honeydew excretion, and sooty mold development.",
        ),
        DiseaseInfo(
            class_idx=124,
            name="Wheat \u2014 Black rust",
            crop="Wheat",
            is_healthy=False,
            chemical_treatment=["Propiconazole 25EC (1 ml/L)", "Tebuconazole 25.9EC (1 ml/L)", "Hexaconazole 5EC (1 ml/L)", "Mancozeb 75WP (2 g/L)"],
            organic_treatment=["Sulfur 80WP dusting (2.5 g/L)", "Resistant cultivars", "Avoid dense planting to reduce microclimate humidity"],
            severity="High",
            description="Pathogen characterized by powdery pustules (uredinia/telia) erupting through the epidermal surface of Wheat leaves.",
        ),
        DiseaseInfo(
            class_idx=125,
            name="Wheat \u2014 Brown rust",
            crop="Wheat",
            is_healthy=False,
            chemical_treatment=["Propiconazole 25EC (1 ml/L)", "Tebuconazole 25.9EC (1 ml/L)", "Hexaconazole 5EC (1 ml/L)", "Mancozeb 75WP (2 g/L)"],
            organic_treatment=["Sulfur 80WP dusting (2.5 g/L)", "Resistant cultivars", "Avoid dense planting to reduce microclimate humidity"],
            severity="High",
            description="Pathogen characterized by powdery pustules (uredinia/telia) erupting through the epidermal surface of Wheat leaves.",
        ),
        DiseaseInfo(
            class_idx=126,
            name="Wheat \u2014 Flag smut",
            crop="Wheat",
            is_healthy=False,
            chemical_treatment=["Propiconazole 25EC (1 ml/L)", "Tebuconazole 25.9EC (1 ml/L)", "Hexaconazole 5EC (1 ml/L)", "Mancozeb 75WP (2 g/L)"],
            organic_treatment=["Sulfur 80WP dusting (2.5 g/L)", "Resistant cultivars", "Avoid dense planting to reduce microclimate humidity"],
            severity="High",
            description="Pathogen characterized by powdery pustules (uredinia/telia) erupting through the epidermal surface of Wheat leaves.",
        ),
        DiseaseInfo(
            class_idx=127,
            name="Wheat \u2014 Leaf blight",
            crop="Wheat",
            is_healthy=False,
            chemical_treatment=["Mancozeb 75WP (2.5 g/L)", "Azoxystrobin 18.2% + Difenoconazole 11.4% SC (1 ml/L)", "Carbendazim 12% + Mancozeb 63% WP (Saaf 2 g/L)"],
            organic_treatment=["Neem oil 1500 ppm (3 ml/L)", "Bordeaux mixture 1%", "Trichoderma viride foliar spray (5 g/L)", "Pruning diseased lower leaves"],
            severity="Moderate",
            description="Fungal infection producing circular to irregular chlorotic lesions, necrotic spots, or foliar blighting on Wheat leaves.",
        ),
        DiseaseInfo(
            class_idx=128,
            name="Wheat \u2014 Mite",
            crop="Wheat",
            is_healthy=False,
            chemical_treatment=["Spiromesifen 22.9SC (1 ml/L)", "Propargite 57EC (2 ml/L)", "Abamectin 1.9EC (0.5 ml/L)"],
            organic_treatment=["Neem oil 1500 ppm (3 ml/L)", "Wettable sulfur (2.5 g/L)", "Predatory mites (Phytoseiidae)"],
            severity="Moderate",
            description="Mite infestation causing micro-punctures on Wheat leaves, resulting in stippling, webbing, and bronzing.",
        ),
        DiseaseInfo(
            class_idx=129,
            name="Wheat \u2014 Powdery mildew",
            crop="Wheat",
            is_healthy=False,
            chemical_treatment=["Mancozeb 75WP (2.5 g/L)", "Azoxystrobin 18.2% + Difenoconazole 11.4% SC (1 ml/L)", "Carbendazim 12% + Mancozeb 63% WP (Saaf 2 g/L)"],
            organic_treatment=["Neem oil 1500 ppm (3 ml/L)", "Bordeaux mixture 1%", "Trichoderma viride foliar spray (5 g/L)", "Pruning diseased lower leaves"],
            severity="Moderate",
            description="Fungal infection producing circular to irregular chlorotic lesions, necrotic spots, or foliar blighting on Wheat leaves.",
        ),
        DiseaseInfo(
            class_idx=130,
            name="Wheat \u2014 Scab",
            crop="Wheat",
            is_healthy=False,
            chemical_treatment=["Mancozeb 75WP (2.5 g/L)", "Azoxystrobin 18.2% + Difenoconazole 11.4% SC (1 ml/L)", "Carbendazim 12% + Mancozeb 63% WP (Saaf 2 g/L)"],
            organic_treatment=["Neem oil 1500 ppm (3 ml/L)", "Bordeaux mixture 1%", "Trichoderma viride foliar spray (5 g/L)", "Pruning diseased lower leaves"],
            severity="Moderate",
            description="Fungal infection producing circular to irregular chlorotic lesions, necrotic spots, or foliar blighting on Wheat leaves.",
        ),
        DiseaseInfo(
            class_idx=131,
            name="Wheat \u2014 Stem fly",
            crop="Wheat",
            is_healthy=False,
            chemical_treatment=["Mancozeb 75WP (2.5 g/L)", "Azoxystrobin 18.2% + Difenoconazole 11.4% SC (1 ml/L)", "Carbendazim 12% + Mancozeb 63% WP (Saaf 2 g/L)"],
            organic_treatment=["Neem oil 1500 ppm (3 ml/L)", "Bordeaux mixture 1%", "Trichoderma viride foliar spray (5 g/L)", "Pruning diseased lower leaves"],
            severity="Moderate",
            description="Fungal infection producing circular to irregular chlorotic lesions, necrotic spots, or foliar blighting on Wheat leaves.",
        ),
        DiseaseInfo(
            class_idx=132,
            name="Wheat \u2014 Yellow rust",
            crop="Wheat",
            is_healthy=False,
            chemical_treatment=["Propiconazole 25EC (1 ml/L)", "Tebuconazole 25.9EC (1 ml/L)", "Hexaconazole 5EC (1 ml/L)", "Mancozeb 75WP (2 g/L)"],
            organic_treatment=["Sulfur 80WP dusting (2.5 g/L)", "Resistant cultivars", "Avoid dense planting to reduce microclimate humidity"],
            severity="High",
            description="Pathogen characterized by powdery pustules (uredinia/telia) erupting through the epidermal surface of Wheat leaves.",
        ),
        DiseaseInfo(
            class_idx=133,
            name="Wheat \u2014 Healthy",
            crop="Wheat",
            is_healthy=True,
            chemical_treatment=[],
            organic_treatment=[],
            severity="None",
            description="Healthy, vigorous Wheat foliage showing robust chlorophyll development with no symptoms of fungal, bacterial, viral infection, or insect pest infestation.",
        ),
    ]

    # Fast lookup dict
    _by_idx: ClassVar[dict[int, DiseaseInfo]] = {}

    @classmethod
    def _ensure_index(cls):
        if not cls._by_idx:
            cls._by_idx = {d.class_idx: d for d in cls.DISEASES}

    @classmethod
    def get_by_index(cls, idx: int) -> DiseaseInfo | None:
        cls._ensure_index()
        if idx in cls._by_idx:
            return cls._by_idx[idx]
        # Dynamic fallback for safety
        if 0 <= idx < len(cls.DISEASES):
            return cls.DISEASES[idx]
        return None

    @classmethod
    def get_all_names(cls) -> list[str]:
        return [d.name for d in cls.DISEASES]

    @classmethod
    def get_class_count(cls) -> int:
        return len(cls.DISEASES)

    @classmethod
    def estimate_chemical_cost(cls, d: DiseaseInfo | None) -> str:
        """Estimate realistic market treatment cost in ₹/Acre per application for Maharashtra."""
        if not d or d.is_healthy or not d.chemical_treatment:
            return "₹0 / Acre (None required)"
        cond_lower = d.name.lower()
        if any(k in cond_lower for k in ["armyworm", "army_worm", "caterpillar", "borer", "dead_heart"]):
            return "₹850 – ₹1,300 / Acre"
        if any(k in cond_lower for k in ["wilt", "fusarium", "rhizome_rot", "pink_rot", "panama", "moko"]):
            return "₹700 – ₹1,100 / Acre"
        if any(k in cond_lower for k in ["late_blight", "blast", "anthracnose"]):
            return "₹650 – ₹950 / Acre"
        if any(k in cond_lower for k in ["rust", "smut", "mildew"]):
            return "₹500 – ₹800 / Acre"
        if any(k in cond_lower for k in ["aphid", "jassid", "whitefly", "thrips", "mite", "mealybug"]):
            return "₹450 – ₹700 / Acre"
        if any(k in cond_lower for k in ["virus", "mosaic", "curl", "streak"]):
            return "₹450 – ₹700 / Acre"
        if d.severity == "Critical":
            return "₹750 – ₹1,200 / Acre"
        if d.severity == "High":
            return "₹600 – ₹900 / Acre"
        return "₹450 – ₹750 / Acre"

    @classmethod
    def estimate_organic_cost(cls, d: DiseaseInfo | None) -> str:
        """Estimate realistic organic bio-input cost in ₹/Acre per application for Maharashtra."""
        if not d or (d.is_healthy and not d.organic_treatment):
            return "₹0 / Acre (Preventive: ₹100 – ₹150 / Acre)"
        cond_lower = d.name.lower()
        if any(k in cond_lower for k in ["armyworm", "army_worm", "caterpillar", "borer"]):
            return "₹280 – ₹480 / Acre"
        if any(k in cond_lower for k in ["wilt", "fusarium", "rhizome_rot", "panama"]):
            return "₹250 – ₹500 / Acre"
        if any(k in cond_lower for k in ["virus", "mosaic", "curl"]):
            return "₹150 – ₹300 / Acre"
        if any(k in cond_lower for k in ["rust", "smut"]):
            return "₹180 – ₹380 / Acre"
        if any(k in cond_lower for k in ["aphid", "jassid", "whitefly", "mite"]):
            return "₹180 – ₹350 / Acre"
        if d.severity == "Critical":
            return "₹300 – ₹550 / Acre"
        if d.severity == "High":
            return "₹250 – ₹450 / Acre"
        return "₹200 – ₹380 / Acre"
